### ISSUE TITLE
command issue

### ISSUE THREAD

**Issue by ashfaqaku** [Hina-softwareEngineer/Rust_Server#1]
as per your given instruction i try this command heroku create YourRepoName \
  --buildpack https://github.com/emk/heroku-buildpack-rust.git                                                    but this command shows error kindly give me some sugetion  »   Error: Unexpected argument: \
 »   See more help with --help

**Comment by Hina-softwareEngineer** [comment]
> as per your given instruction i try this command heroku create YourRepoName
> --buildpack https://github.com/emk/heroku-buildpack-rust.git but this command shows error kindly give me some sugetion » Error: Unexpected argument:
> » See more help with --help

Try to write this command on one line "`heroku create YourRepoName --buildpack https://github.com/emk/heroku-buildpack-rust.git`" or if you want to write on two lines then `
heroku create YourRepoName \

  --buildpack https://github.com/emk/heroku-buildpack-rust.git
`, 

\(forward-slash) in the command is mandatory if you write on two lines.
